#
# Copyright (C) 2015 Javier González <javier@javigon.com>
#
# Makefile for the kernel secure hardware (sechw) drivers
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#

obj-$(CONFIG_ARM_TRUSTZONE) 		+= trustzone/
