#
# Copyright (C) 2014 Javier González <javier@javigon.com>
#
# Makefile for the Open Virtualization TrustZone kernel driver
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
obj-$(CONFIG_TRUSTZONE_SIERRAWARE) += otz_client_main.o
